### ISSUE TITLE
Expected token on_kw, not on_const at [[4, 8], :on_const, "URI"] (Rufo::Bug)

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#17]
Related to #16, in my actual code, I got a different error with this pattern of calling a converter method that looks like a constant, e.g. `Kernel#URI`, `Kernel#Array`, `Kernel#Integer`, ...

```
require 'uri'

def to_uri(string)
  uri = URI(string) rescue return
  uri
end
```

The generated stack trace is:

```
~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2395:in `bug': Expected token on_kw, not on_const at [[4, 8], :on_const, "URI"] (Rufo::Bug)
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2390:in `check'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2192:in `consume_keyword'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:285:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:591:in `visit_suffix'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:186:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2379:in `indent_after_space'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:512:in `visit_assign_value'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:474:in `visit_assign'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:174:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2321:in `block in indent_body'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2305:in `indent'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2320:in `indent_body'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:965:in `visit_bodystmt'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:225:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:1303:in `visit_def_from_name'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:1229:in `block in visit_def'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2479:in `push_hash'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:1228:in `visit_def'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:251:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:102:in `visit'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:85:in `format'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:95:in `format'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:16:in `format_stdin'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:8:in `run'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/exe/rufo:4:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.2.6/bin/rufo:22:in `load'
  from ~/.rvm/gems/ruby-2.2.6/bin/rufo:22:in `<main>'
  from ~/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by meineerde** [comment]
Hmmm, turns out, this is the exact same issue as #19. The error is caused by the trailing `rescue`, not use of the converter method.
