### ISSUE TITLE
Expected token on_kw, not on_period at [[2, 5], :on_period, "."] (Rufo::Bug)

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#19]
The following code triggers a bug:

```
def copy_if_possible(obj)
  obj.dup rescue obj
end
```

The generated stack trace is:

```
~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2395:in `bug': Expected token on_kw, not on_period at [[2, 5], :on_period, "."] (Rufo::Bug)
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2390:in `check'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2192:in `consume_keyword'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:593:in `visit_suffix'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:186:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2321:in `block in indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2305:in `indent'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2320:in `indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:965:in `visit_bodystmt'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:225:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1303:in `visit_def_from_name'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1229:in `block in visit_def'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2479:in `push_hash'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1228:in `visit_def'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:251:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:102:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:85:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/command.rb:95:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/command.rb:16:in `format_stdin'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/command.rb:8:in `run'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/exe/rufo:4:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `load'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `<main>'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by meineerde** [comment]
A similar bug occurs with an inline rescue of a method called on an instance variable:

```ruby
@file.close rescue nil
```

The stack trace in this case is:

````
~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2395:in `bug': Expected token on_kw, not on_ivar at [[47, 10], :on_ivar, "@file"] (Rufo::Bug)
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2390:in `check'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2173:in `consume_token'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:156:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:150:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:591:in `visit_suffix'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:186:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2321:in `block in indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2305:in `indent'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2320:in `indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:877:in `visit_do_block'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:219:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:810:in `visit_call_with_block'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:213:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:335:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:319:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2321:in `block in indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2305:in `indent'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2320:in `indent_body'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:965:in `visit_bodystmt'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:225:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1303:in `visit_def_from_name'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1229:in `block in visit_def'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:2479:in `push_hash'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.5/lib/rufo/formatter.rb:1228:in `visit_def'
  ...
```
