### ISSUE TITLE
Unhandled node: string_dvar at [[2, 1], :on_embvar, "#"]

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#25]
My hobby today: Find some idiosyncratic but valid Ruby syntax which upsets rufo :)

There is an optional "special" way to embed the contents of instance or class variables into a String without using "full" interpolation:

```ruby
@foo = :foo
"#@foo"
```

Similar to instance variables, you can also use class variables (`@@foo`) or global variables (`$foo`) here.

Formatting this with rufo results in the following error:

```
~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:2571:in `bug': Unhandled node: string_dvar at [[2, 1], :on_embvar, "#"] (Rufo::Bug)
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:343:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:369:in `block (2 levels) in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:2653:in `push_node'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:368:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:440:in `visit_string_literal_end'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:432:in `visit_string_literal'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:130:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:369:in `block (2 levels) in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:2653:in `push_node'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:368:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:102:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:85:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:96:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:16:in `format_stdin'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:8:in `run'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/exe/rufo:4:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `load'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `<main>'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by asterite** [comment]
Nice! I didn't know that.
