### ISSUE TITLE
Rufo doesn't like rational numbers

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#29]
Rational numbers have their own literal syntax:

```ruby
3.141592r
```

Rufo apparently doesn't like this at all and raises:

```
~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:2571:in `bug': Unhandled node: @rational at [[1, 0], :on_rational, "3.141592r"] (Rufo::Bug)
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:343:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:369:in `block (2 levels) in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:2653:in `push_node'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:368:in `block in visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `each_with_index'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:352:in `visit_exps'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:102:in `visit'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/formatter.rb:85:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:96:in `format'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:16:in `format_stdin'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/lib/rufo/command.rb:8:in `run'
  from ~/.rvm/gems/ruby-2.4.1/gems/rufo-0.0.11/exe/rufo:4:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `load'
  from ~/.rvm/gems/ruby-2.4.1/bin/rufo:22:in `<main>'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by asterite** [comment]
And it seems it didn't know about imaginary eithers ;-)
