### ISSUE TITLE
Expected token on_tstring_beg, not on_tstring_content at [[2, 0], :on_tstring_content, "text\n"]

### ISSUE THREAD

**Issue by splattael** [asterite/rufo#41]
## Reproduction

(From bundler's source)

```
{ "a" => <<EOF,
text
EOF
  "b" => 23
}
```

## Failure

```
You've found a bug!
It happened while trying to format the file foo.rb
Please report it to https://github.com/asterite/rufo/issues with code that triggers it

bundler: failed to load command: exe/rufo (exe/rufo)
Rufo::Bug: Expected token on_tstring_beg, not on_tstring_content at [[2, 0], :on_tstring_content, "text\n"]
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2705:in `bug'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2700:in `check'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2442:in `consume_token'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:447:in `visit_string_literal'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:143:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:1785:in `visit_hash_key_value'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:302:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2139:in `block in visit_literal_elements'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2135:in `each'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2135:in `each_with_index'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2135:in `visit_literal_elements'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:1763:in `block in visit_hash'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2816:in `push_hash'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:1762:in `visit_hash'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:300:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:393:in `block (2 levels) in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2808:in `push_node'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:392:in `block in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:376:in `each'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:376:in `each_with_index'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:376:in `visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:102:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:83:in `format'
  /home/peter/devel/rufo/lib/rufo/command.rb:104:in `format'
  /home/peter/devel/rufo/lib/rufo/command.rb:60:in `format_file'
  /home/peter/devel/rufo/lib/rufo/command.rb:49:in `block in format_args'
  /home/peter/devel/rufo/lib/rufo/command.rb:48:in `each'
  /home/peter/devel/rufo/lib/rufo/command.rb:48:in `format_args'
  /home/peter/devel/rufo/lib/rufo/command.rb:10:in `run'
  exe/rufo:4:in `<top (required)>'
```

**Comment by splattael** [comment]
:green_heart: Thanks!

The fix of this issue and #44 will enable `rufo` to format [bundler](https://github.com/bundler/bundler) :sparkles: :sunglasses:
