### ISSUE TITLE
Expected token on_int, not on_kw at [[1, 6], :on_kw, "then"]

### ISSUE THREAD

**Issue by splattael** [asterite/rufo#51]
While running `rufo` on Ruby's codebase I found the following error.

## Reproduction

```ruby
if 1
then 2
end
```

## Failure

```
You've found a bug!
Please report it to https://github.com/asterite/rufo/issues with code that triggers it

bundler: failed to load command: exe/rufo (exe/rufo)
Rufo::Bug: Expected token on_int, not on_kw at [[1, 6], :on_kw, "then"]
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2908:in `bug'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2903:in `check'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2627:in `consume_token'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:167:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:450:in `block (2 levels) in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:3015:in `push_node'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:449:in `block in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `each'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `each_with_index'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2828:in `block in indent_body'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2812:in `indent'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2827:in `indent_body'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2367:in `visit_if_or_unless'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:2341:in `visit_if'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:321:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:450:in `block (2 levels) in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:3015:in `push_node'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:449:in `block in visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `each'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `each_with_index'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:433:in `visit_exps'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:157:in `visit'
  /home/peter/devel/rufo/lib/rufo/formatter.rb:137:in `format'
  /home/peter/devel/rufo/lib/rufo/command.rb:113:in `format'
  /home/peter/devel/rufo/lib/rufo/command.rb:25:in `format_stdin'
  /home/peter/devel/rufo/lib/rufo/command.rb:17:in `run'
  /home/peter/devel/rufo/lib/rufo/command.rb:6:in `run'
  exe/rufo:4:in `<top (required)>'
Command exited with non-zero status 1
```

**Comment by asterite** [comment]
I had no idea that was valid Ruby code 😮

**Comment by splattael** [comment]
@asterite I fear Ruby's codebase contains some other syntax gems :gem: 

More to come :grin:
