### ISSUE TITLE
Unhandled node: [:command, [:@ident, "redirect_to",...

### ISSUE THREAD

**Issue by ZogStriP** [asterite/rufo#8]
I tried running `rufo` on [Discourse](https://github.com/discourse/discourse) and got this error message regarding [this file](https://github.com/discourse/discourse/blob/master/app/controllers/about_controller.rb).

```
You've found a bug!
It happened while trying to format the file ./app/controllers/about_controller.rb
Please report it to https://github.com/asterite/rufo/issues with code that triggers it

/Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2276:in `bug': Unhandled node: [:command, [:@ident, "redirect_to", [8, 11]], [:args_add_block, [[:method_add_arg, [:fcall, [:@ident, "path", [8, 23]]], [:arg_paren, [:args_add_block, [[:string_literal, [:string_content, [:@tstring_content, "/login", [8, 29]]]]], false]]]], false]] at [[8, 11], :on_ident, "redirect_to"] (Rufo::Bug)
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:298:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1686:in `block in visit_control_keyword'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2182:in `indent'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1685:in `visit_control_keyword'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1659:in `visit_return'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:277:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:569:in `visit_suffix'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:172:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:323:in `block in visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each_with_index'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2202:in `block in indent_body'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2186:in `indent'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2201:in `indent_body'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:943:in `visit_bodystmt'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:215:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1266:in `visit_def_from_name'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1192:in `block in visit_def'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2360:in `push_hash'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1191:in `visit_def'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:241:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:323:in `block in visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each_with_index'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2202:in `block in indent_body'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2186:in `indent'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:2201:in `indent_body'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:943:in `visit_bodystmt'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:215:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1177:in `maybe_inline_body'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:1147:in `visit_class'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:233:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:323:in `block in visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `each_with_index'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:307:in `visit_exps'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:102:in `visit'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/formatter.rb:85:in `format'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:92:in `format'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:57:in `format_file'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:49:in `block in format_args'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:48:in `each'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:48:in `format_args'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/lib/rufo/command.rb:10:in `run'
	from /Users/zogstrip/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rufo-0.0.3/exe/rufo:4:in `<top (required)>'
	from /Users/zogstrip/.rbenv/versions/2.4.1/bin/rufo:22:in `load'
	from /Users/zogstrip/.rbenv/versions/2.4.1/bin/rufo:22:in `<main>'
```

**Comment by mjago** [comment]
reduces to 
```ruby
return a b
```
Works fine with parenthesis.
